Update names.txt
hadiMh/developersnames pull request #14
Opened 2024-05-14 15:06 UTC by AliMohammadinezhad

add my own name to the file names.txt according to Mr. Haji hoseini course

2024-06-07 16:40 UTC, lenis03 requested changes

2024-06-07 16:40 UTC, lenis03 commented on names.txt
> +Ali Mohammadi
To merge your pull request, you just need to add your first name to the end of the file!

2024-06-19 19:56 UTC, AliPrj approved these changes
🙏🏻❤️

2024-06-19 20:00 UTC, AliPrj commented
❤️👏🏻

2024-06-21 17:08 UTC, AliPrj approved these changes

2024-07-01 15:19 UTC, closed without merging