update names.txt file
hadiMh/developersnames pull request #19
Opened 2024-06-24 14:14 UTC by zahra-eslamian

I added my name to names.txt file.

2024-07-01 15:20 UTC, AliMohammadinezhad commented
just name!

2024-07-06 05:30 UTC, lenis03 requested changes

2024-07-06 05:30 UTC, lenis03 commented on names.txt
> +Zahra Eslamian
Hello, please just add your first name to the end of the file!

2024-07-08 13:54 UTC, lenis03 approved these changes

2024-07-08 13:54 UTC, lenis03 commented
Thank you for using our Git course, and I hope you have been satisfied with the course so far. 🙏🏻

2024-07-08 13:54 UTC, merged