Update names.txt
hadiMh/developersnames pull request #2
Opened 2024-03-08 09:16 UTC by maryamjafari-kh

add my name

2024-03-09 22:07 UTC, lenis03 commented
Hi, I hope you are doing well.
Thank you for using our Git course, and I hope you have been satisfied with the course so far.
To merge your pull request, you just need to add your first name to the end of the file 🙏
Thank you very much.

2024-03-10 15:33 UTC, lenis03 requested changes

2024-03-10 15:33 UTC, lenis03 commented on names.txt
> +maryam jafari
Hello, please just add your first name to the end of the file!

2024-06-19 20:02 UTC, AliPrj approved these changes
❤️👏🏻

2024-06-19 20:03 UTC, closed without merging

2024-06-19 20:03 UTC, AliPrj commented
💪🏻👏🏻❤️🤝🏻